# Generated by Django 5.1.2 on 2024-11-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
